### ISSUE TITLE
Subject Template Cutting Off Values

### ISSUE THREAD

**Issue by ashfordneil** [UQComputingSociety/subject-guide#12]
The template used to generate each subject page needs to wrap text when it gets too long. Currently (for example, see ENGG1100 with full course coordinator list), any field that is too long gets trimmed.

**Comment by TRManderson** [comment]
ENGG1300 too

**Comment by wisebaldone** [comment]
@matthew-lake is their an easy way to fix this or would manual editing need to be done.

**Comment by wisebaldone** [comment]
@ashfordneil can you confirm this is still an issue?

**Comment by TRManderson** [comment]
Lgtm, what was your fix @wbo?

**Comment by ashfordneil** [comment]
@wisebaldone it is no longer an issue 😄

**Comment by wisebaldone** [comment]
fixed it differently in two places, basically issue was that the text was in a table which dont autowrap

```
\begin{tabular}{ l l } // left, left
    \parbox[l]{12cm}{Really long text to be wrapped after 12cm which is floated to the left.} // this was needed to ensure it was floating to the left which method below doesn't guarantee
\end{tabular}
```

and this was the other way

```
\begin{tabular}{ p{6cm} c p{7cm}}
    Some really long text that will wrap within 6cm,  next section will be centered and last section wrapping in a 7cm box.
\end{tabular}
```
