### ISSUE TITLE
Automatic Building

### ISSUE THREAD

**Issue by wisebaldone** [UQComputingSociety/subject-guide#6]
- Builds of pdf for publishment
- Builds of pdf's for pull requests also

**Comment by TRManderson** [comment]
See https://github.com/UQComputingSociety/webhooks/issues/4

**Comment by TRManderson** [comment]
So I'm all good to add this to hookbot, as soon as we decide on how we're keeping it. I've installed dependencies for `latexmk` onto the UQCS server.

**Comment by wisebaldone** [comment]
was gonna docker it up and use travis to do the hard lifting, but if you wanna use server.

**Comment by TRManderson** [comment]
Gotta host it somewhere, may as well build it where we're hosting it. There's also a not unreasonable chance I'll end up setting up Jenkins.

**Comment by wisebaldone** [comment]
This is a lengthy request.

But if you do setup the butler, can he build the pulls and make the pdf accessible so things can be checked in actual pdf without building on own system.

**Comment by TRManderson** [comment]
As in build the PDF not only for master, but for PRs too?

**Comment by wisebaldone** [comment]
yep, means pull requests will be let through faster

**Comment by TRManderson** [comment]
Sounds like it's time I set up a proper deployment strategy.

**Comment by TRManderson** [comment]
This has now been a thing for a while: https://jenkins.trm.io/job/UQCS%20subject%20guide/
